image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
  - echo "CI started..." 
  - export GRADLE_USER_HOME=`pwd`/.gradle
  
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script: 
    - chmod +x ./gradlew
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
  tags:
    - grad
  
test:
  stage: test
  script:     
    -  chmod +x ./gradlew
    - ./gradlew check
  tags:
    - grad

deploy:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/catme-app-test-server.git || true
    - git push -f heroku develop:master
  only:
     - develop
  tags:
    - grad